name: java-example
on: [push]
jobs:
  check-java-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
