name: Java Example
on:
  push:
    branches:
    - release/**
jobs:
  test-java-version:
    runs-on: ubuntu-latest
    steps:
      - name: Configura Java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Imprime JAVA_HOME
        run: echo $JAVA_HOME
      - name: Imprime Java version
        run: java -version

