#Nesse workflow, o GitHub Actions verifica o código enviado, 
#instala a estrutura de teste de bats e executa um comando básico 
#para gerar a versão de bats: bats -v.

name: learn-github-actions  
on:
  push:
    branches:
    - examples/**
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
